baseURL = "https://healthcouncilcanada.ca/"
languageCode = "en-us"
title = "Health Council Canada"
theme = "healthcouncil"
disableKinds = ["RSS"]
paginate = 25

[taxonomies]
  theme = "themes"
  type = "types"
