baseURL = "https://healthcouncilcanada.ca/"
languageCode = "en-us"
title = "Health Council Canada"
theme = "healthcouncil"
disableKinds = ["RSS"]
sectionPagesMenu = "sections"
paginate = 25

[taxonomies]
  category = "categories"
  type = "types"
